version: "3.8"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Config/nginx.conf:/etc/nginx/nginx.conf
      - proxy_logs:/var/log/nginx
    networks:
      - public
      - private
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./Frontend
    networks:
      - private
    deploy:
      replicas: 1

  backend:
    build: ./Backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    volumes:
      - backend_logs:/var/log/backend
    networks:
      - private
    deploy:
      replicas: 2

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - private
  
  

networks:
  public:
    driver: bridge

  private:
    driver: bridge
    internal: true


