apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: jenkins
data:
  init.sql: |
    USE exampledb;
    CREATE TABLE test_table (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    );

    INSERT INTO test_table (name) VALUES ('John Doe'), ('Jane Smith');



---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: jenkins
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkCg==  # "rootpassword" base64 encoded
  MYSQL_DATABASE: ZXhhbXBsZWRiCg==           # "exampledb" base64 encoded
  MYSQL_USER: dXNlcgo=                   # "user" base64 encoded
  MYSQL_PASSWORD: dXNlcnBhc3N3b3JkCg==       # "userpassword" base64 encoded


---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: jenkins
type: Opaque
data:
  DB_HOST: bXlzcWwtMAo=  # "database" base64 encoded
  DB_USER: dXNlcgo=      # "user" base64 encoded
  DB_PASSWORD: dXNlcnBhc3N3b3JkCg==  # "userpassword" base64 encoded
  DB_NAME: ZXhhbXBsZWRiCg==           # "exampledb" base64 encoded
  PORT: NTAwMAo=                      # "5000" base64 encodedec
